export interface ShipmentQueueItem {
  id: string;
  shipmentId: string;
  customerName: string;
  productName: string;
  carrier: string;
  badge: 'Express' | 'Ground' | 'Standard';
  badgeType: 'express' | 'neutral';
  isActive?: boolean;
}

export interface PackageItem {
  id: string;
  title: string;
  subtitle: string;
  sku: string;
  weight: string;
  quantity: number;
  image: string;
}

export interface ActivityLogEvent {
  id: string;
  time: string;
  title: string;
  location: string;
  isCurrent?: boolean;
}

export interface ShippingState {
  activeShipmentId: string;
  activeFilter: 'All Shipments' | 'Warehouse A' | 'Priority Only';
}

export const INITIAL_SHIPMENT_QUEUE: ShipmentQueueItem[] = [
  {
    id: 'shp-1',
    shipmentId: '#LX-9902',
    customerName: 'Elena von Berg',
    productName: 'Onyx Grand Tote',
    carrier: 'DHL International',
    badge: 'Express',
    badgeType: 'express',
    isActive: true,
  },
  {
    id: 'shp-2',
    shipmentId: '#LX-8841',
    customerName: 'Julian Moretti',
    productName: 'Chronos Gold XL',
    carrier: 'FedEx Priority',
    badge: 'Ground',
    badgeType: 'neutral',
    isActive: false,
  },
  {
    id: 'shp-3',
    shipmentId: '#LX-8839',
    customerName: 'Sophia Lorenza',
    productName: 'Silk Atelier Scarf',
    carrier: 'UPS Saver',
    badge: 'Standard',
    badgeType: 'neutral',
    isActive: false,
  },
];

export const INITIAL_PACKAGE_CONTENTS: PackageItem[] = [
  {
    id: 'pkg-1',
    title: 'Onyx Grand Tote',
    subtitle: 'Handcrafted Black Leather',
    sku: 'LUX-BAG-001',
    weight: '1.2kg',
    quantity: 1,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuADEMbdS2qMkYzZ0QUPQ8xfy5I2j-GHCaFdv-FKnQ5r_e45oVG3ID-FRgfe8rLrcwFBdFMXzYDLIfWy28pi3fz5Nt0_hQbBvwhG_XX-ckwG71KQXYz-C3qj45ChVmbFkCOf9eBuFHXJeALBl3JmOPsbWTb7QYAGKTR8EZvDeelTx-IltsAdz6Oy6_6FkjyL9zEgkXvXfkpEDz3NJ1vyoaha_9heTW7OeEQQWycD3sS9kT-4DN23QQEb-vYhtTco4AkU3M1BsTM-bVHJ',
  },
  {
    id: 'pkg-2',
    title: 'Silk Dust Protector',
    subtitle: 'Complimentary Accessory',
    sku: 'LUX-ACC-900',
    weight: '0.1kg',
    quantity: 1,
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCD2dpVQ___c5eh9-Vx1soVJ5JDCep_IqnGCWmsaP8MPIYPWAU6RrT-9QIOM6l7PhCTniQKiWgq0utAXJKZJMkSnSidg4dt4U1Oi-Xv6axwr8v4Iv28QRjhT_zN_k199rpgIMf_lhNvJ_TBoTDhhVYrrcpFGvOs7mAF6FY8n0PlirJ4z5RcTV-ASx3Ys2XDqaR_27Fl7EGaMeDbLEFzFJgfSpL-cAO-tNLUYlkkczfVrS3KBv1eyTa6GII-_OrtufZ7rzkaR-qTARpX',
  },
];

export const INITIAL_ACTIVITY_EVENTS: ActivityLogEvent[] = [
  { id: 'act-1', time: '14:20 PM', title: 'Label generated by Mark T.', location: 'Berlin Dispatch Center', isCurrent: true },
  { id: 'act-2', time: '11:15 AM', title: 'Packed in Box #42-S', location: 'Paris Atelier', isCurrent: false },
  { id: 'act-3', time: '09:02 AM', title: 'Quality Control Passed', location: 'QC Station 4', isCurrent: false },
];

export const INITIAL_SHIPPING_STATE: ShippingState = {
  activeShipmentId: 'shp-1',
  activeFilter: 'All Shipments',
};
